[package]
name = "origin-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
origin-core = { path = "../origin-core" }
origin-compiler = { path = "../origin-compiler" }
origin-fast = { path = "../origin-fast" }
origin-kernel = { path = "../origin-kernel" }
